//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOperations
    {
        public int ROID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> OID { get; set; }
    
        public virtual Operations Operations { get; set; }
        public virtual Operations Operations1 { get; set; }
        public virtual Rols Rols { get; set; }
    }
}
