//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public int SID { get; set; }
        public string SName { get; set; }
        public Nullable<int> GID { get; set; }
    
        public virtual Grades Grades { get; set; }
    }
}
