//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UID { get; set; }
        public string UName { get; set; }
        public string URealName { get; set; }
        public string ULastName { get; set; }
        public string UEmail { get; set; }
        public string UPassword { get; set; }
        public System.DateTime UDate { get; set; }
        public Nullable<bool> UStatus { get; set; }
        public Nullable<int> RID { get; set; }
        public string UConfirmPassword { get; set; }
        public Nullable<int> GID { get; set; }
    
        public virtual Grades Grades { get; set; }
        public virtual Rols Rols { get; set; }
    }
}
